nodeLinker: node-modules
compressionLevel: mixed
enableGlobalCache: false
npmRegistryServer: "https://registry.npmjs.org"
npmPublishRegistry: "https://registry.npmjs.org"

supportedArchitectures:
  os: [darwin, linux, win32]
  cpu: [x64, arm64]

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard

