name: PR Check

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.editorconfig'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Verify commit messages
        uses: wagoid/commitlint-github-action@v6

      - name: Check dependencies
        run: |
          yarn check:deps:all
          yarn list --pattern "*" --depth=0 > deps-list.txt.

      - name: Detect package changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            core:
              - 'packages/core/**'
            animation:
              - 'packages/animation/**'
            debounce:
              - 'packages/debounce/**'
            html:
              - 'packages/html/**'
            listener:
              - 'packages/listener/**'
            logger:
              - 'packages/logger/**'
            pointer:
              - 'packages/pointer/**'
            scrollable:
              - 'packages/scrollable/**'
            state:
              - 'packages/state/**'
            throttle:
              - 'packages/throttle/**'
            signal:
              - 'packages/signal/**'
            'batch-scheduler':
              - 'packages/batch-scheduler/**'

      - name: Build changed packages
        if: steps.changes.outputs['batch-scheduler'] == 'true' ||steps.changes.outputs.signal == 'true' || steps.changes.outputs.core == 'true' || steps.changes.outputs.animation == 'true' || steps.changes.outputs.debounce == 'true' || steps.changes.outputs.html == 'true' || steps.changes.outputs.listener == 'true' || steps.changes.outputs.logger == 'true' || steps.changes.outputs.pointer == 'true' || steps.changes.outputs.scrollable == 'true' || steps.changes.outputs.state == 'true' || steps.changes.outputs.throttle == 'true'
        run: yarn build

      - name: Bundle size check
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Performance check
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: 'packages/*/dist/**/*.{js,css,html,json}'
          strip-hash: ''
          minimum-change-threshold: 100
